services:
    asdoria_catalog_mode.state_machine.guard.catalog_mode_checker:
        public: true
        class: Latelier22\SyliusVitrineModePlugin\StateMachine\Guard\VitrineModeChecker
        calls:
            - ['setVitrineModeChecker', ['@Latelier22\SyliusVitrineModePlugin\Checker\VitrineModeChecker']]
