services:
    Latelier22\SyliusVitrineModePlugin\Validator\Constraints\VitrineModeOrderItemValidator:
        calls:
            - [setVitrineModeChecker, ['@Latelier22\SyliusVitrineModePlugin\Checker\VitrineModeChecker']]
        tags:
            - { name: 'validator.constraint_validator', alias: 'asdoria_catalog_mode_is_enabled' }
