winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            guard:
                vitrine_mode_checker:
                    on: ["address", "skip_shipping", "select_shipping", "skip_payment", "select_payment", "complete"]
                    do: ["@latelier22_vitrine_mode.state_machine.guard.vitrine_mode_checker", "disabledVitrineMode"]
sylius_ui:
    events:
        sylius.admin.channel.form.second_column_content:
            blocks:
                latelier22_vitrine_mode_channel:
                    template: "@Latelier22SyliusVitrineModePlugin/Admin/Channel/_vitrineMode.html.twig"
                    priority: 15
